version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smartstudydb
    ports:
      - "5432:5432"

  backend:
    build: ../backend/SmartStudy.API
    ports:
      - "5000:8080"
    depends_on:
      - db

  frontend:
    build: ../frontend
    ports:
      - "3000:3000"